runtime: php55
api_version: 1
threadsafe: true
env: flex

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
  
 runtime.config:
   document_root:web